name: NoxUtils
version: '2.2.0'
main: me.iris.noxUtils.NoxUtils
api-version: '1.21'
authors: [ Iris ]
description: An API to communicate with Noxesium clients
website: https://github.com/BlockybombDEV/NoxUtils
depend:
  - CommandAPI
